# Generated by Django 5.0.1 on 2024-02-05 22:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RarePlant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('common_name', models.CharField(blank=True, default='', max_length=200)),
                ('botanical_name', models.CharField(default='', max_length=200, unique=True)),
                ('acquisition_date', models.DateField()),
                ('rarity', models.TextField(default='', verbose_name="help_text='Common', 'Uncommon', 'Rare', 'Very Rare', 'Extinct in the Wild.'")),
                ('sunlight', models.CharField(default='', help_text='Sunlight requirements, e.g., full sun, partial shade, full shade.', max_length=255)),
                ('waterings', models.CharField(default='', help_text='Watering frequency, e.g., twice a week, daily, every two weeks.', max_length=255)),
                ('temperature', models.CharField(default='', help_text='Optimal temperature range, e.g., 65-75°F (18-24°C).', max_length=255)),
                ('humidity', models.CharField(default='', help_text='Preferred humidity level, e.g., high, medium, low.', max_length=255)),
                ('soil_needs', models.CharField(default='', help_text='Soil type and pH preference, e.g., well-draining, loamy soil with a pH of 6.0-7.0.', max_length=255)),
                ('myth_name', models.CharField(default='', max_length=200)),
                ('description', models.TextField()),
                ('origin_country', models.CharField(blank=True, default='', max_length=100)),
                ('uses', models.TextField(blank=True, default='', help_text='Describe traditional or contemporary uses of the plant related to the mythology, including medicinal, ornamental, or other utilitarian purposes.')),
                ('natural_history', models.TextField(blank=True, default='', help_text="Provide information on the plant's natural history, including its discovery, historical range, and changes in its distribution or abundance over time.")),
                ('cultivation', models.TextField(blank=True, default='', help_text='Outline cultivation methods tied to the plant’s historical or mythological significance, if any, including traditional practices or symbolic cultivation methods.')),
                ('notes', models.TextField(blank=True, default='', null=True)),
            ],
        ),
    ]
