# Generated by Django 5.0.1 on 2024-02-05 22:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rareplant',
            name='rarity',
            field=models.TextField(default='', verbose_name="help_text='Common', 'Uncommon', 'Rare', 'Very Rare', 'Extinct in the Wild.' "),
        ),
    ]
