# Generated by Django 5.0.1 on 2024-02-05 22:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_alter_rareplant_rarity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rareplant',
            name='rarity',
            field=models.TextField(default='', help_text='"Common", "Uncommon", "Rare", "Very Rare", "Extinct in the Wild."'),
        ),
    ]
