# Generated by Django 5.0.1 on 2024-02-06 09:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0004_alter_rareplant_rarity'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rareplant',
            name='cultivation',
        ),
        migrations.RemoveField(
            model_name='rareplant',
            name='humidity',
        ),
        migrations.RemoveField(
            model_name='rareplant',
            name='myth_name',
        ),
        migrations.RemoveField(
            model_name='rareplant',
            name='natural_history',
        ),
        migrations.RemoveField(
            model_name='rareplant',
            name='notes',
        ),
        migrations.RemoveField(
            model_name='rareplant',
            name='origin_country',
        ),
        migrations.RemoveField(
            model_name='rareplant',
            name='soil_needs',
        ),
        migrations.RemoveField(
            model_name='rareplant',
            name='sunlight',
        ),
        migrations.RemoveField(
            model_name='rareplant',
            name='temperature',
        ),
        migrations.RemoveField(
            model_name='rareplant',
            name='uses',
        ),
        migrations.RemoveField(
            model_name='rareplant',
            name='waterings',
        ),
        migrations.AlterField(
            model_name='rareplant',
            name='description',
            field=models.TextField(default='', help_text='leaf shape, flower color, growth habit, and any distinctive features.'),
        ),
        migrations.AlterField(
            model_name='rareplant',
            name='rarity',
            field=models.CharField(choices=[('Common', 'Common'), ('Uncommon', 'Uncommon'), ('Rare', 'Rare'), ('Very Rare', 'Very Rare'), ('Extinct in the Wild', 'Extinct in the Wild')], default='', help_text='"Common", "Uncommon", "Rare", "Very Rare", "Extinct in the Wild."'),
        ),
        migrations.CreateModel(
            name='PlantCare',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sunlight', models.CharField(default='', help_text='Sunlight requirements, e.g., full sun, partial shade, full shade.', max_length=255)),
                ('waterings', models.CharField(default='', help_text='Watering frequency, e.g., twice a week, daily, every two weeks.', max_length=255)),
                ('temperature', models.CharField(default='', help_text='Optimal temperature range, e.g., 65-75°F (18-24°C).', max_length=255)),
                ('humidity', models.CharField(default='', help_text='Preferred humidity level, e.g., high, medium, low.', max_length=255)),
                ('soil_needs', models.CharField(default='', help_text='Soil type and pH preference, e.g., well-draining, loamy soil with a pH of 6.0-7.0.', max_length=255)),
                ('RarePlant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.rareplant')),
            ],
        ),
        migrations.CreateModel(
            name='PlantOrigins',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('origin_country', models.CharField(blank=True, default='', max_length=100)),
                ('uses', models.TextField(blank=True, default='', help_text='Describe traditional or contemporary uses of the plant related to the mythology, including medicinal, ornamental, or other utilitarian purposes.')),
                ('natural_history', models.TextField(blank=True, default='', help_text="Provide information on the plant's natural history, including its discovery, historical range, and changes in its distribution or abundance over time.")),
                ('cultivation', models.TextField(blank=True, default='', help_text='Outline cultivation methods tied to the plant’s historical or mythological significance, if any, including traditional practices or symbolic cultivation methods.')),
                ('myth_name', models.CharField(blank=True, default='', max_length=200, null=True)),
                ('description', models.TextField()),
                ('notes', models.TextField(blank=True, default='', null=True)),
                ('RarePlant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.rareplant')),
            ],
        ),
    ]
