# Generated by Django 5.0.1 on 2024-02-06 10:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0005_remove_rareplant_cultivation_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='PlantOrigins',
            new_name='PlantOrigin',
        ),
    ]
