# Generated by Django 5.0.1 on 2024-02-06 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0006_rename_plantorigins_plantorigin'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='plantorigin',
            name='description',
        ),
        migrations.AlterField(
            model_name='rareplant',
            name='rarity',
            field=models.CharField(choices=[('Common', 'Common'), ('Uncommon', 'Uncommon'), ('Rare', 'Rare'), ('Very Rare', 'Very Rare'), ('Extinct in the Wild', 'Extinct in the Wild')], default=''),
        ),
    ]
