# Generated by Django 5.0.1 on 2024-02-06 10:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0007_remove_plantorigin_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plantcare',
            name='RarePlant',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='main_app.rareplant'),
        ),
        migrations.AlterField(
            model_name='plantorigin',
            name='RarePlant',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='main_app.rareplant'),
        ),
    ]
