# Generated by Django 5.0.1 on 2024-02-06 11:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0008_alter_plantcare_rareplant_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='PlantCare',
            new_name='PlantCultivation',
        ),
        migrations.CreateModel(
            name='PlantNurture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('soil_ph', models.DecimalField(decimal_places=2, max_digits=4)),
                ('cleaned', models.BooleanField(default=False)),
                ('met_required_light', models.BooleanField(default=False)),
                ('met_required_humidity', models.BooleanField(default=False)),
                ('music_played', models.CharField(blank=True, max_length=255, null=True)),
                ('overall_appearance', models.TextField()),
                ('RarePlant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='nurtures', to='main_app.rareplant')),
            ],
        ),
    ]
