# Generated by Django 5.0.1 on 2024-02-06 11:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0009_rename_plantcare_plantcultivation_plantnurture'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='plantnurture',
            options={'ordering': ['-date']},
        ),
    ]
