# Generated by Django 5.0.1 on 2024-02-06 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0010_alter_plantnurture_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plantcultivation',
            name='temperature',
            field=models.CharField(default='', help_text='Optimal temperature range, e.g., 65-75°F (18-24°C) option + shift + 8 for degree symbol.', max_length=255),
        ),
    ]
