# Generated by Django 5.0.1 on 2024-02-06 14:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0011_alter_plantcultivation_temperature'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='plantnurture',
            options={},
        ),
    ]
