# Generated by Django 5.0.1 on 2024-02-06 15:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0012_alter_plantnurture_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='plantnurture',
            options={'ordering': ['-date']},
        ),
    ]
