# Generated by Django 5.0.1 on 2024-02-06 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0013_alter_plantnurture_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='plantcultivation',
            name='fertilizer_needs',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='plantnurture',
            name='watered',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
