# Generated by Django 5.0.1 on 2024-02-06 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0014_plantcultivation_fertilizer_needs_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='plantnurture',
            name='soil_moisture',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
