# Generated by Django 5.0.1 on 2024-02-06 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0015_plantnurture_soil_moisture'),
    ]

    operations = [
        migrations.AddField(
            model_name='rareplant',
            name='poisonous',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AddField(
            model_name='rareplant',
            name='toxic',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
