# Generated by Django 5.0.1 on 2024-02-06 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0016_rareplant_poisonous_rareplant_toxic'),
    ]

    operations = [
        migrations.CreateModel(
            name='MusicPlaylist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('Genre', models.CharField(max_length=20)),
                ('length', models.CharField(max_length=20)),
            ],
        ),
    ]
