# Generated by Django 5.0.1 on 2024-02-06 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0017_musicplaylist'),
    ]

    operations = [
        migrations.AlterField(
            model_name='musicplaylist',
            name='length',
            field=models.DurationField(),
        ),
    ]
