# Generated by Django 5.0.1 on 2024-02-06 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0018_alter_musicplaylist_length'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='plantnurture',
            name='music_played',
        ),
        migrations.AddField(
            model_name='plantnurture',
            name='music_played',
            field=models.ManyToManyField(to='main_app.musicplaylist'),
        ),
    ]
